### ISSUE TITLE
[Windows] Failed to generate data with Python3.6

### ISSUE THREAD

**Issue by LukasS91** [end2you/end2you#4]
Hi,

it seems like there is an issue with using moviepy and python 3.6 under Windows. I had trouble generating the data (.wav files) with moviepys audio reader. After spending some time googling I finally found out that my python version (latest 3.6) and Windows might be causing this issue. So I upgraded to the latest python version (3.7) supportet by tensorflow 1.15 and as of now everything is running as it should.

Maybe suggest using python=3.7 in your documentation? At least for Windows users.

**Comment by paldxc782** [comment]
> Hi,
> 
> it seems like there is an issue with using moviepy and python 3.6 under Windows. I had trouble generating the data (.wav files) with moviepys audio reader. After spending some time googling I finally found out that my python version (latest 3.6) and Windows might be causing this issue. So I upgraded to the latest python version (3.7) supportet by tensorflow 1.15 and as of now everything is running as it should.
> 
> Maybe suggest using python=3.7 in your documentation? At least for Windows users.

I also encountered a problem in generating the data. My environment settings are the same as yours. But I still can't succeed, I guess there is something wrong with the format of my data_file. Can I ask you for your data_file to lend me a reference?

**Comment by LukasS91** [comment]
Unfortunately I can't share my data. I also have to say that I stopped using this implementation soon after. I had to make several adjustments to the code to get everything running (I don't remember if only for the train part or for the data generation as well). Then the evaluation part didn't work and I decided to implement everything by myself rather than fixing this code.

**Comment by paldxc782** [comment]
I understand, thanks. I will try another method.
