### ISSUE TITLE
About pre-train model of audio modality

### ISSUE THREAD

**Issue by r09522817** [end2you/end2you#6]
Hi, I found that you only provide the visual pre-train model of SEWA here. 
I would be grateful if you could share the audio modality pre-train model here! 
Look forward to hearing from you.
thanks !

**Comment by tzirakis** [comment]
Hello, thank you for you comment and request. We intend to upload pre-train audio models later this week.

**Comment by r09522817** [comment]
That's a great news! 
Thank you so much.
